apiVersion: v1
kind: Pod
metadata:
  name: my-pod-network
spec:
  containers:
    - name: my-c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-chirag; sleep 5; done"]
    - name: my-c01
      image: httpd
      ports:
        - containerPort: 80



###

