import json
import boto3
import os
from urllib.parse import unquote_plus
from datetime import datetime
import math

def lambda_handler(event, context):
    """
    Lambda function that processes S3 upload events and sends email notifications via SNS
    
    Flow:
    1. S3 upload triggers this Lambda function
    2. Lambda extracts file information from S3 event
    3. Lambda sends email notification via SNS
    4. Returns success/error response
    """
    
    # Initialize AWS service clients
    sns_client = boto3.client('sns')
    s3_client = boto3.client('s3')
    
    # Get environment variables (set by Terraform)
    sns_topic_arn = os.environ.get('SNS_TOPIC_ARN')
    region = os.environ.get('REGION', 'us-east-1')
    
    print(f"Processing S3 event in region: {region}")
    print(f"SNS Topic ARN: {sns_topic_arn}")
    
    def format_file_size(size_bytes):
        """Convert bytes to human readable format"""
        if size_bytes == 0:
            return "0 B"
        size_names = ["B", "KB", "MB", "GB", "TB"]
        i = int(math.floor(math.log(size_bytes, 1024)))
        p = math.pow(1024, i)
        s = round(size_bytes / p, 2)
        return f"{s} {size_names[i]}"
    
    try:
        # Process each S3 event record
        for record in event['Records']:
            # Extract S3 event information
            event_name = record['eventName']                    # e.g., 's3:ObjectCreated:Put'
            bucket_name = record['s3']['bucket']['name']        # S3 bucket name
            object_key = unquote_plus(record['s3']['object']['key'])  # File name (URL decoded)
            object_size = record['s3']['object']['size']        # File size in bytes
            
            # Get additional file information from S3
            try:
                # Get object metadata
                s3_response = s3_client.head_object(Bucket=bucket_name, Key=object_key)
                last_modified = s3_response['LastModified'].strftime('%Y-%m-%d %H:%M:%S UTC')
                content_type = s3_response.get('ContentType', 'Unknown')
            except Exception as e:
                print(f"Error getting object metadata: {str(e)}")
                last_modified = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
                content_type = 'Unknown'
            
            # Convert file size to human readable format
            formatted_size = format_file_size(object_size)
            
            print(f"Processing file: {object_key} ({formatted_size}) in bucket: {bucket_name}")
            
            # Create email message
            email_subject = f"New File Uploaded to S3: {object_key}"
            
            email_message = f"""Hello!

A new file has been uploaded to your S3 bucket.

File Details:
• File Name: {object_key}
• Bucket: {bucket_name}
• File Size: {formatted_size}
• Content Type: {content_type}
• Upload Time: {last_modified}
• Event Type: {event_name}

AWS Console Link:
https://s3.console.aws.amazon.com/s3/object/{bucket_name}?region={region}&prefix={object_key}

S3 Bucket Link:
https://s3.console.aws.amazon.com/s3/buckets/{bucket_name}?region={region}

This notification was automatically generated by your Lambda function.

Best regards,
Your AWS Lambda S3 Monitor"""
            
            # Send SNS notification (email)
            try:
                sns_response = sns_client.publish(
                    TopicArn=sns_topic_arn,
                    Subject=email_subject,
                    Message=email_message
                )
                
                message_id = sns_response['MessageId']
                print(f"Email notification sent successfully! Message ID: {message_id}")
                
            except Exception as sns_error:
                print(f"Error sending SNS notification: {str(sns_error)}")
                raise sns_error
        
        # Return success response
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'S3 event processed successfully',
                'processed_files': len(event['Records']),
                'sns_topic': sns_topic_arn
            })
        }
        
    except Exception as e:
        # Log error and return error response
        error_message = f"Error processing S3 event: {str(e)}"
        print(f"ERROR: {error_message}")
        
        # Try to send error notification
        try:
            error_subject = "Lambda S3 Processing Error"
            error_email = f"""An error occurred while processing S3 upload event:

Error: {str(e)}
Time: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
Function: {context.function_name if context else 'Unknown'}

Please check CloudWatch logs for more details."""
            
            sns_client.publish(
                TopicArn=sns_topic_arn,
                Subject=error_subject,
                Message=error_email
            )
        except:
            print("Failed to send error notification via SNS")
        
        return {
            'statusCode': 500,
            'body': json.dumps({
                'error': error_message
            })
        }