apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  clusterIP: None # make a hardless service
  ports:
  - port: 27017
    targetPort: 27017

# I added five directory
# sudo mkdir -p /mnt/data/mongodb-{0..4}
# sudo chmod 777 -p /mnt/data/mongodb-{0..4}
