kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: my-app-nodeport    # This should match the label of the pods you want to expose
  type: NodePort  # Other options: NodePort, LoadBalancer, etc.