apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5


# Statement:-
# This YAML file defines a Kubernetes Pod named "liveness1" that contains a single container running the nginx image. 
# The liveness probe checks if the TCP socket on port 80 is open every 5 seconds, starting 5 seconds after the container
#  has started. If the TCP socket is not open, the liveness probe will fail, indicating that the container 
# is not healthy.

# In simple words:-
# The container starts and the liveness probe checks if the TCP socket on port 80 is open every 5 seconds. 
# If the socket is not open, the liveness probe will fail.

# If both port is different then time pod restarts