kind: Pod
apiVersion: v1
metadata:
  name: liveness1
  labels:
    app: liveness1
spec:
  containers:
  - name: liveness1
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
