apiVersion: v1
kind: Pod
metadata:
  name: initcontainerpod
  labels:
    name: initcontainerpod
spec:
  containers:
    - name: main-container
      image: busybox
      command: ['sh', '-c', 'echo Main container is running; sleep 3600']
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'echo Init container is running; sleep 5']

# commands:-
# k apply -f initcontainer.yml --dry-run=client
# kubectl get pod initcontainerpod -o wide
# kubectl describe pod initcontainerpod
# kubectl logs initcontainerpod -c init-container

# print environment variable from main container
# kubectl exec -it initcontainerpod -- printenv

# Once Init container created, we can't modify it, we need to delete and recreate the pod

# kubectl get pods -w (live watch)