apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding2
  namespace: default
subjects:
- kind: User
  name: chirag
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader2
  apiGroup: rbac.authorization.k8s.io
