apiVersion: v1
kind: PersistentVolume
metadata:
  name: registory-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  hostPath:
    path: "/home/chirag/Documents/RathiData/udata/Kubernet/KubernetWithPiyush/repos"
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registory-pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
