apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "chirag"
  hostPath:
    path: "/home/ubuntu"
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
spec:
  storageClassName: "chirag"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
