kind: Pod
apiVersion: v1
metadata:
  name: liveness-pod
spec:
  containers:
    - name: c1
      image: rockylinux:9
      command: 
        - /bin/bash
        - -c
        - while true; do echo Hello-chirag; sleep 5; done
      volumeMounts:
        - name: config-volume
          mountPath: /tmp/mysecret
  volumes:
    - name: config-volume
      secret:
        secretName: mysecret
# This config uses Secret as a volume in a Pod

# kubectl exec -it liveness-pod -- /bin/bash
# [root@liveness-pod /]# cd /tmp/mysecret/
# [root@liveness-pod mysecret]# ls
# password.txt  username.txt
# [root@liveness-pod mysecret]# cat password.txt 
# password
# [root@liveness-pod mysecret]# 
