This is a sample configuration file.

# kubectl create configmap myapp --from-file=sample.conf

# kubectl get configmap (This command lists all ConfigMaps in the current namespace)

# kubectl describe configmap myapp (This command shows detailed information about the ConfigMap named 'myapp')