apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebs-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-08b2875c868fc24d8
    fsType: ext4




    # kubectl get pv