apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations:
    kubernetes.io/service-account.name: build-sa #actual name enter your service account 
type: kubernetes.io/service-account-token


# commands:
# kubectl apply -f secret.yml
# kubectl get secret
# kubectl describe secret build-robot-secret