apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    myname: Chirag
  template:
    metadata:
      labels:
        myname: Chirag
    spec:
      containers:
        - name: c02
          image: ubuntu
          command:
            - /bin/bash
            - -c
            - while true; do echo Hello-Chirag; sleep 5; done