kind: LimitRange
apiVersion: v1
metadata:
  name: resource-limits
spec:
  limits:
  - max:
      memory: 1Gi
    min:
      memory: 500Mi
    type: Container

# This LimitRange sets maximum and minimum memory limits for containers in the namespace.
# Containers must request at least 500Mi of memory and cannot exceed 1Gi of memory
# when specifying their resource requirements.
# Maximum memory limit is set to 1Gi and minimum memory request is set to 500Mi.m.

# This LimitRange sets default CPU limits and requests for containers in the namespace.
# If a container does not specify its own CPU limits or requests, it will inherit these defaults.
# Default CPU limit is set to 1 CPU and default CPU request is set to 500m.