kind: Deployment
apiVersion: apps/v1
metadata:
  name: resourcepod1
spec:
  replicas: 3
  selector:
    matchLabels:
      objtype: resourcepod1
  template:
    metadata:
      labels:
        objtype: resourcepod1
    spec:
      containers:
        - name: resourcecontainer1
          image: nginx:latest
          resources:
            requests:
              cpu: "150m"
          ports:
            - containerPort: 80

# If you define a ResourceQuota for a namespace, all Pods created in that namespace must adhere to the resource limits and requests specified 
# in the ResourceQuota.
# In this case, the ResourceQuota allows a maximum of 200m CPU requests and 400m CPU limits.
# The Pod defined here requests 150m CPU, which is within the allowed limit of the ResourceQuota.
# Therefore, this Pod configuration is valid and can be created in the namespace with the specified ResourceQuota.

# Scenario Analysis:
# Total limit = 400m
# This pod request each 150m CPU
# 3 * 150m = 450m > 400m Not allowed
# Hence we need to reduce the replicas to 2