apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-volume
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /tmp/my-volume
          name: my-volume

    - name: c2
      image: httpd
      ports:
        - containerPort: 8080
      command:
        - /bin/sh
        - -c
        - |
          sed -i 's/Listen 80/Listen 8080/' /usr/local/apache2/conf/httpd.conf && \
          httpd-foreground
      volumeMounts:
        - mountPath: /tmp/my-volume
          name: my-volume

  volumes:
    - name: my-volume
      emptyDir: {}
